import = ["/home/logans/.alacritty.d/alacritty.yml"]

[colors.bright]
black = "#292929"
blue = "#7ebbfa"
cyan = "#4dcad7"
green = "#72cc9e"
magenta = "#bba8f5"
red = "#f59a92"
white = "#dedede"
yellow = "#b4bf6a"

[colors.normal]
black = "#181818"
blue = "#5894d0"
cyan = "#08a2af"
green = "#49a478"
magenta = "#9481cb"
red = "#ca736d"
white = "#b8b8b8"
yellow = "#8d9742"

[colors.primary]
background = "#181818"
foreground = "#9c9c9c"

[font]
size = 13.0

[font.normal]
family = "Mononoki Nerd Font Mono"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 4
y = 4
