#!/usr/bin/env bash

REAL_SWAY_BIN="/usr/bin/sway"

# run sway with a login shell env (sources .profile)
if command -v zsh &> /dev/null; then
  # This weird syntax is needed to ensure that arguments are correctly quoted
  # in the nested shell. Any arguments passed after `-c <executable>` are set as
  # positional arguments in the new shell, effectively perfectly passing them
  # through to the subshell, which we can then expand with the normal `"$@"`
  # syntax.
  exec zsh -l -c "$REAL_SWAY_BIN \"\$@\"" _ "$@"
else
  exec "$REAL_SWAY_BIN" "$@"
fi
